spring:
  application:
    name: oms_usermanagement

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=user_db;trustServerCertificate=true
    username: MALULEKI\malul
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080